### ISSUE TITLE
Make FDP-connector interfaces compliant with Browser-fs interfaces

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fairdrive-opfs#4]
https://github.com/fairDataSociety/fdp-browser-fs-api/blob/main/src/index.ts 

-  Adapter,
-  FileSystemFileHandleAdapter,
-  FileSystemFolderHandleAdapter,
-  WriteChunk,

Do they have interface for "drives" so we can use "pods" as "drives" ? @molekilla ?

**Comment by molekilla** [comment]
complete
